# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*/
os: WMF 5

install:
 - cinst pester -y
 - cinst virtualbox
 - cinst vagrant
 - vagrant plugin install vagrant-dsc

build: false

# Test with native PS version
test_script:
  - ps: vagrant version
  - ps: vagrant up